# Generated by Django 4.1.7 on 2023-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('plant_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=60)),
                ('add_date', models.DateField()),
                ('last_watered', models.DateField(null=True)),
                ('water_reminder', models.DateTimeField(null=True)),
            ],
        ),
    ]
