# Generated by Django 4.1.7 on 2023-04-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='plant_name',
        ),
        migrations.AddField(
            model_name='plants',
            name='common_name',
            field=models.CharField(default='plant', max_length=100),
        ),
        migrations.AddField(
            model_name='plants',
            name='image_url',
            field=models.CharField(default='url', max_length=2000),
        ),
        migrations.AddField(
            model_name='plants',
            name='scientific_name',
            field=models.CharField(default='plant', max_length=100),
        ),
    ]
